---
containers:
- name: openshift_excluder_disable
  image: rhel7-ansible
  image_version: latest
  ansible_groups:
    - openshift_excluder_disable
  dockerfile: Dockerfile
- name: openshift_excluder_enable
  image: rhel7-ansible
  image_version: latest
  ansible_groups:
    - openshift_excluder_enable
  dockerfile: Dockerfile
- name: openshift_excluder_upgrade_34_35
  image: rhel7-ansible
  image_version: latest
  ansible_groups:
    - openshift_excluder_upgrade_34_35
  dockerfile: Dockerfile
scenarios:
##########################################
# Check excluders are correctly disabled #
##########################################
- name: "Disable excluders during installation"
  vars:
    r_openshift_excluder_service_type: atomic-openshift
  containers:
  - openshift_excluder_disable
  playbook: playbooks/disable_excluders.yml
- name: "Disable excluders during installation (docker excluder disabled)"
  vars:
    r_openshift_excluder_service_type: atomic-openshift
    r_openshift_excluder_enable_docker_excluder: false
  containers:
  - openshift_excluder_disable
  playbook: playbooks/disable_excluders.yml
- name: "Disable excluders during installation (openshift excluder disabled)"
  vars:
    r_openshift_excluder_service_type: atomic-openshift
    r_openshift_excluder_enable_openshift_excluder: false
  containers:
  - openshift_excluder_disable
  playbook: playbooks/disable_excluders.yml
#########################################
# Check excluders are correctly enabled #
#########################################
- name: "Enable excluders during installation"
  vars:
    r_openshift_excluder_service_type: atomic-openshift
  containers:
  - openshift_excluder_enable
  playbook: playbooks/enable_excluders.yml
- name: "Enable excluders during installation (ignoring docker excluder)"
  vars:
    r_openshift_excluder_service_type: atomic-openshift
    r_openshift_excluder_enable_docker_excluder: false
  containers:
  - openshift_excluder_enable
  playbook: playbooks/enable_excluders.yml
- name: "Enable excluders during installation (ignoring openshift excluder)"
  vars:
    r_openshift_excluder_service_type: atomic-openshift
    r_openshift_excluder_enable_openshift_excluder: false
  containers:
  - openshift_excluder_enable
  playbook: playbooks/enable_excluders.yml
######################################################################
# Check excluders are correctly disabled and enabled (in that order) #
######################################################################
- name: "Disable and enable excluders during installation"
  vars:
    r_openshift_excluder_service_type: atomic-openshift
  containers:
  - openshift_excluder_enable
- name: "Disable and enable excluders during installation (ignoring docker excluder)"
  vars:
    r_openshift_excluder_service_type: atomic-openshift
    r_openshift_excluder_enable_docker_excluder: false
  containers:
  - openshift_excluder_enable
- name: "Disable and enable excluders during installation (ignoring openshift excluder)"
  vars:
    r_openshift_excluder_service_type: atomic-openshift
    r_openshift_excluder_enable_openshift_excluder: false
  containers:
  - openshift_excluder_enable
##########################################################
# Check excluders are correctly upgraded from 3.4 to 3.5 #
##########################################################
- name: Upgrade excluders from 3.4 to 3.5
  vars:
    r_openshift_excluder_service_type: atomic-openshift
  containers:
  - openshift_excluder_upgrade_34_35
  playbook: playbooks/upgrade_excluders.yml
