---
- include_role:
    name: openshift_node_facts
  vars:
    r_openshift_node_facts_annotations: "{{ openshift_node_annotations | default(omit) }}"
    r_openshift_node_facts_debug_level: "{{ openshift_node_debug_level | default(openshift.common.debug_level) }}"
    r_openshift_node_facts_iptables_sync_period: "{{ openshift_node_iptables_sync_period | default(omit) }}"
    r_openshift_node_facts_kubelet_args: "{{ openshift_node_kubelet_args | default(omit) }}"
    r_openshift_node_facts_labels: "{{ lookup('oo_option', 'openshift_node_labels') | default( openshift_node_labels | default(none), true) }}"
    r_openshift_node_facts_oreg_url: "{{ oreg_url_node | default(oreg_url) | default(omit) }}"
    r_openshift_node_facts_schedulable: "{{ openshift_schedulable | default(openshift_scheduleable) | default(omit) }}"
    r_openshift_node_facts_sdn_mtu: "{{ openshift_node_sdn_mtu | default(omit) }}"
    r_openshift_node_facts_osn_storage_plugin_deps: "{{ osn_storage_plugin_deps | default(omit) }}"
    r_openshift_node_facts_set_node_ip: "{{ openshift_set_node_ip | default(omit) }}"
    r_openshift_node_facts_osn_image: "{{ osn_image | default(omit) }}"
    r_openshift_node_facts_osn_ovs_image: "{{ osn_ovs_image | default(omit) }}"
    r_openshift_node_facts_proxy_mode: "{{ openshift_node_proxy_mode | default(omit) }}"
    r_openshift_node_facts_local_quota_per_fsgroup: "{{ openshift_node_local_quota_per_fsgroup | default(omit) }}"
    r_openshift_node_facts_dns_ip: "{{ openshift_dns_ip | default(omit) }}"
    r_openshift_node_facts_env_vars: "{{ openshift_node_env_vars | default(omit) }}"
