---
# input variables:
# - openshift_master_upgrade_pre_hook
# - openshift.common.is_containerized
# - master_config_hook
# - openshift_master_upgrade_hook
# - openshift.common.rolling_restart_mode
# - openshift_master_upgrade_post_hook

# Run the pre-upgrade hook if defined:
- debug: msg="Running master pre-upgrade hook {{ openshift_master_upgrade_pre_hook }}"
  when: openshift_master_upgrade_pre_hook is defined

- include: "{{ openshift_master_upgrade_pre_hook }}"
  when: openshift_master_upgrade_pre_hook is defined

- include: rpm_upgrade.yml component=master
  when: not openshift.common.is_containerized | bool

  # to define openshift_master_facts_default_predicates
  # and openshift_master_facts_default_priorities
- include_vars: ../../../../roles/openshift_master_facts/vars/main.yml

- include: upgrade_scheduler.yml

- include: "{{ master_config_hook }}"
  when: master_config_hook is defined

  # vars for roles/openshift_master/tasks/systemd_units.yml
- include_vars: ../../../../roles/openshift_master/vars/main.yml

- name: Update systemd units
  include: ../../../../roles/openshift_master/tasks/systemd_units.yml

- include: migrate_certificates.yml

# Run the upgrade hook prior to restarting services/system if defined:
- debug: msg="Running master upgrade hook {{ openshift_master_upgrade_hook }}"
  when: openshift_master_upgrade_hook is defined

- include: "{{ openshift_master_upgrade_hook }}"
  when: openshift_master_upgrade_hook is defined

- include: ../../openshift-master/restart_hosts.yml
  when: openshift.common.rolling_restart_mode == 'system'

- include: ../../openshift-master/restart_services.yml
  when: openshift.common.rolling_restart_mode == 'services'

# Run the post-upgrade hook if defined:
- debug: msg="Running master post-upgrade hook {{ openshift_master_upgrade_post_hook }}"
  when: openshift_master_upgrade_post_hook is defined

- include: "{{ openshift_master_upgrade_post_hook }}"
  when: openshift_master_upgrade_post_hook is defined
